---
title: "arealstatistik und bfs"
output: html_document
date: "2023-01-19"
---

```{r}

library(tidyverse)
library(sp)
library(sf)
library(tmap)
library(leaflet)
library(igraph)
library(nngeo)
library(lwgeom)
library(lubridate)
library(progress)
library(raster)
library(terra)

```

# Arealstatistik
```{r}
        
pb <- progress_bar$new(
  format = "  downloading [:bar] :percent eta: :eta",
  total = 100, clear = FALSE, width= 60)
for (i in 1:100) {
  pb$tick()
  arealst_csv <-read.csv("C:\\Users\\t97oe\\OneDrive - Universität Zürich UZH\\Dokumente\\uzh Master\\Geo 511 Thesis\\data\\geodata\\Arealstatistik\\ag-b-00.03-37-area-csv.csv", sep = ";")
}

arealst <- arealst_csv %>% dplyr::select(E, N,AS18_27)
arealst <- arealst %>% filter(E >= 2668545 & E <=2693042)
arealst <- arealst %>% filter(N >= 1243820 & N <= 1258270)

arealst_shp <- st_as_sf(arealst, coords = c("E","N"), crs=2056)
st_write(arealst_shp,"C:\\Users\\t97oe\\OneDrive - Universität Zürich UZH\\Dokumente\\uzh Master\\Geo 511 Thesis\\data\\geodata\\Arealstatistik\\as18_27_clip.shp")


arealst_r <- arealst %>% rasterFromXYZ(crs = 2056)


arealst_r_res <- arealst %>% mutate(E = E+50,
                                    N = N+50)
arealst_r_res <- arealst_r_res %>% rasterFromXYZ(crs = 2056)



writeRaster(arealst_r_res,"C:\\Users\\t97oe\\OneDrive - Universität Zürich UZH\\Dokumente\\uzh Master\\Geo 511 Thesis\\data\\geodata\\Arealstatistik\\as18_27_clip.tif", overwrite=TRUE)
plot(arealst_r)

```

# distance to residential area = 2
```{r}
# # Find the nearest cell of the raster with value 46
# r_value2 <- raster::extract(arealst_r, which(arealst_r[] == 2))

# convert the raster to sf object
r_sf <- as(arealst_r, "SpatialPolygonsDataFrame")
r_sf <- st_as_sf(r_sf, crs = 2056)
r_sf <- st_set_crs(r_sf, 2056)
r_sf <- r_sf %>% filter(AS18_27 == 2)
AVnetz <- st_transform(kt_av, 2056)
AVnetz <- st_crop(AVnetz, st_bbox(polygon))

# strava_geo_h <- tail(strava_geo)
## find the nearest feature 
nearest_r2 <- st_nearest_feature(AVnetz, r_sf)
# nearest_r2_h <- st_nearest_feature(strava_geo_h, r_sf)
## calculate the distance
# strava_geo$dist_2_resid <- strava_geo %>% st_distance(strava_geo, r_sf[nearest_r2,])

# strava_geo_h <- strava_geo_h %>% mutate(resi_g = r_sf$geometry[nearest_r2])
# strava_geo_h <- strava_geo_h %>% mutate(dist_2_resid = st_distance(geometry,resi_g, by_element = TRUE))



AVnetz <- AVnetz %>% mutate(resi_g = r_sf$geometry[nearest_r2])
AVnetz <- AVnetz %>% mutate(dist_2_resid = st_distance(geometry,resi_g, by_element = TRUE))


pb <- progress_bar$new(
  format = "  downloading [:bar] :percent eta: :eta",
  total = 100, clear = FALSE, width= 60)
for (i in 1:100) {
  pb$tick()
nearest_r2 <- st_nearest_feature(AVnetz, r_sf)
AVnetz <- AVnetz %>% mutate(resi_g = r_sf$geometry[nearest_r2])
AVnetz <- AVnetz %>% mutate(dist_2_resid = st_distance(geometry,resi_g, by_element = TRUE))
}

```
# distance to green space = 10

```{r}

g_sf <- as(arealst_r, "SpatialPolygonsDataFrame")
g_sf <- st_as_sf(g_sf, crs = 2056)
g_sf <- st_set_crs(g_sf, 2056)
g_sf <- g_sf %>% filter(AS18_27 == 10)

# strava_geo_h <- tail(strava_geo)
## find the nearest feature 
# nearest_r2 <- st_nearest_feature(strava_geo, g_sf)
# nearest_r2_h <- st_nearest_feature(strava_geo_h, r_sf)

# strava_geo_h <- strava_geo_h %>% mutate(resi_g = r_sf$geometry[nearest_r2])
# strava_geo_h <- strava_geo_h %>% mutate(dist_2_resid = st_distance(geometry,resi_g, by_element = TRUE))

# strava_geo <- strava_geo %>% mutate(resi_g = g_sf$geometry[nearest_r2])
# strava_geo <- strava_geo %>% mutate(dist_2_resid = st_distance(geometry,resi_g, by_element = TRUE))

pb <- progress_bar$new(
  format = "  downloading [:bar] :percent eta: :eta",
  total = 100, clear = FALSE, width= 60)
for (i in 1:100) {
  pb$tick()
nearest_r2 <- st_nearest_feature(AVnetz, g_sf)
AVnetz <- AVnetz %>% mutate(green_g = g_sf$geometry[nearest_r2])
AVnetz <- AVnetz %>% mutate(dist_10_green = st_distance(geometry,green_g, by_element = TRUE))
}

st_write(AVnetz, "C:\\Users\\t97oe\\OneDrive - Universität Zürich UZH\\Dokumente\\uzh Master\\Geo 511 Thesis\\data\\geodata\\output\\AVnetz_res_gree_dist.shp")

```
# try of improved green space

```{r}

av_midpoints_green <- av_midpoints_mix_landuse

g_sf_V2 <- as(arealst_r, "SpatialPolygonsDataFrame")
g_sf_V2 <- st_as_sf(g_sf_V2, crs = 2056)
g_sf_V2 <- st_set_crs(g_sf_V2, 2056)
g_sf_V2 <- g_sf_V2 %>% filter(AS18_27 %in% c(10,15,16,19,20,21,22,23,24))


pb <- progress_bar$new(
  format = "  downloading [:bar] :percent eta: :eta",
  total = 100, clear = FALSE, width= 60)
for (i in 1:100) {
  pb$tick()
nearest_r2_V2 <- st_nearest_feature(av_midpoints_green, g_sf_V2)
av_midpoints_green <- av_midpoints_green %>% mutate(green_g_V2 = g_sf_V2$geometry[nearest_r2_V2])
av_midpoints_green <- av_midpoints_green %>% mutate(dist_10_green = st_distance(geometry,green_g_V2, by_element = TRUE))
}

st_write(AVnetz, "C:\\Users\\t97oe\\OneDrive - Universität Zürich UZH\\Dokumente\\uzh Master\\Geo 511 Thesis\\data\\geodata\\output\\AVnetz_res_gree_dist.shp")



```

# mixed land use parameter

```{r}

mix_landuse <- raster("C:\\Users\\t97oe\\OneDrive - Universität Zürich UZH\\Dokumente\\uzh Master\\Geo 511 Thesis\\data\\geodata\\Arealstatistik\\mixed_landuse_500m.tif")

av_midpoints <- st_read("C:\\Users\\t97oe\\OneDrive - Universität Zürich UZH\\Dokumente\\uzh Master\\Geo 511 Thesis\\data\\geodata\\KTZH_AV_Netz\\points\\points.shp")
av_midpoints <- st_crop(av_midpoints, st_bbox(polygon))
av_midpoints_mix_landuse <- select(av_midpoints, "OBJECTID", "geometry")



# Define the reclassification matrix
m <- matrix(c(1,1,1,
              2,2,2,
              3,3,3,
              4,255,0), ncol=3, byrow=TRUE)

# Reclassify the raster
mix_landuse_reclass <- reclassify(mix_landuse, m)
plot(mix_landuse_reclass)

av_midpoints_mix_landuse$mix_value <- raster::extract(mix_landuse_reclass, av_midpoints_mix_landuse)
av_midpoints_mix_landuse <- right_join(av_midpoints_mix_landuse, as.data.frame(AVnetz_counts%>% select("OBJECTID")))
av_midpoints_mix_landuse <- av_midpoints_mix_landuse %>% st_drop_geometry()
av_midpoints_mix_landuse$mix_value <- ifelse(is.na(av_midpoints_mix_landuse$mix_value),0,av_midpoints_mix_landuse$mix_value)

av_midpoints_mix_landuse <- st_crop(av_midpoints_mix_landuse, st_bbox(polygon))






```








# StatPop BFS im hektarraster

```{r}

statpop_csv <- read.csv("C:\\Users\\t97oe\\OneDrive - Universität Zürich UZH\\Dokumente\\uzh Master\\Geo 511 Thesis\\data\\geodata\\BFS_statpop\\ag-b-00.03-vz2021statpop\\STATPOP2021.csv", sep = ";")

av_midpoints_r <- st_read("C:\\Users\\t97oe\\OneDrive - Universität Zürich UZH\\Dokumente\\uzh Master\\Geo 511 Thesis\\data\\geodata\\KTZH_AV_Netz\\points\\points.shp")
av_midpoints_r <- st_crop(av_midpoints_r, st_bbox(polygon))
av_midpoints_r <- av_midpoints_r %>% select(OBJECTID, geometry)

statpop <- statpop_csv
statpop <- statpop %>% filter(E_KOORD >= 2668545 & E_KOORD <=2693042)
statpop <- statpop %>% filter(N_KOORD >= 1243820 & N_KOORD <= 1258270)
statpop <- statpop %>% select(E_KOORD, N_KOORD, B21BTOT, B21B11, B21B12, B21BMTOT,B21BM17, B21BM18, B21BM19, B21BWTOT, B21BW17, B21BW18, B21BW19)
statpop <- statpop %>% mutate(Mueber80 = B21BM17+B21BM18+B21BM19)
statpop <- statpop %>% mutate(Wueber80 = B21BW17+B21BW18+B21BW19)
statpop <- statpop %>% mutate(ueber80 = (Mueber80+Wueber80))
                              # /B21BTOT*100)
statpop <- statpop %>% select(E_KOORD, N_KOORD, B21BTOT, B21B11, B21B12, B21BMTOT,B21BWTOT, ueber80)
statpop <- statpop %>% rename(B21CH = B21B11)
statpop <- statpop %>% rename(B21AUSL = B21B12)

```

# rasterize
```{r}


statpop_tot <- statpop %>% dplyr::select(1,2,3) %>%
  rename(x = E_KOORD, y = N_KOORD, PopDens = B21BTOT)
  
statpop_u80 <- statpop %>% dplyr::select(1,2,3,8) %>%
  rename(x = E_KOORD, y = N_KOORD, PopTot = B21BTOT) 



# Load the data and create a Raster object
statpop_tot_r <- statpop_tot %>% rasterFromXYZ(crs = 2056)
statpop_u80_r <- statpop_u80 %>% rasterFromXYZ(crs = 2056)
# Set the projection of the Raster object
projection(statpop_tot_r) <- CRS("+init=EPSG:2056")
projection(statpop_u80_r) <- CRS("+init=EPSG:2056")


# Aggregate the Raster object
statpop_tot_r <- raster::aggregate(statpop_tot_r, fact = 5, fun = sum)
statpop_u80_r <- raster::aggregate(statpop_u80_r, fact = 5, fun = sum)

hist(statpop_tot_r)
hist(pop_u80_AV$u80_perc)


writeRaster(statpop_tot_r,"C:\\Users\\t97oe\\OneDrive - Universität Zürich UZH\\Dokumente\\uzh Master\\Geo 511 Thesis\\data\\geodata\\Arealstatistik\\statpop_R.tiff", overwrite=TRUE)


```

# assign to street segments
```{r}


# Extract raster values for street segments using st_extract()
av_midpoints_r <- st_zm(av_midpoints_r, drop = TRUE)
av_midpoints_r <- st_crop(av_midpoints_r, st_bbox(polygon))
# av_midpoints_r <- av_midpoints_r %>% rownames_to_column()
av_midpoints_r <- av_midpoints_r %>% rownames_to_column(var = "ID")

# statpop_r <- projectRaster(statpop_r, crs = CRS("+init=EPSG:2056"))
pop_dens_AV <- raster::extract(statpop_tot_r, av_midpoints_r, na.rm = TRUE, df = TRUE)
pop_u80_AV <- raster::extract(statpop_u80_r, av_midpoints_r, na.rm = TRUE, df = TRUE)
pop_dens_AV <- pop_dens_AV %>% mutate(ID = as.character(ID))
pop_u80_AV <- pop_u80_AV %>% mutate(ID = as.character(ID))
pop_u80_AV <- pop_u80_AV %>% mutate(u80_perc = (ueber80/PopTot)*100)

av_midpoints_r <- right_join(av_midpoints_r, pop_dens_AV, by= "ID")
av_midpoints_r <- right_join(av_midpoints_r, pop_u80_AV, by= "ID")
av_midpoints_r <- av_midpoints_r %>% dplyr::select(OBJECTID, PopDens, u80_perc, geometry)
# #join to retrieve only the 15427 edges 
# av_midpoints_r <- right_join(av_midpoints_r, as.data.frame(AVnetz_counts%>% select("OBJECTID")))
# av_midpoints_r <- av_midpoints_r %>% st_drop_geometry()
av_midpoints_r$PopDens <- ifelse(is.na(av_midpoints_r$PopDens),0,av_midpoints_r$PopDens)
av_midpoints_r$u80_perc <- ifelse(is.na(av_midpoints_r$u80_perc),0,av_midpoints_r$u80_perc)

```





